### ISSUE TITLE
Список задач

### ISSUE THREAD

**Issue by themanyfaceddemon** [AdventureTimeSS14/space_station_ADT#2]
# Для @AdventureTimeSS14/ert_developteam
# ОТПИСЫВАЙТЕ В КОММЕНТЫ ЗА ЧТО ВЗЯЛИСЬ

## Задачи для переноса [сборки](https://github.com/xtray85/space_station):

- [ ] Добавить больше задач

## Необходимо перенести контент прототипов со старого репозитория. Вы выбираете какую-то фичу и полностью переносите её (прототипы,спрайты, локализация) и кидаете отдельным ПР.
- [ ] Поменять отображение для манифеста и прочего
- [x] Перенос спрайтов https://github.com/AdventureTimeSS14/space_station_ADT/pull/33
- [ ] Перенос прототипов (необходимо разделить на несколько задач)
- [ ] Жужжащий акцент https://github.com/xtray85/space_station/commit/cc9f2204269a2b08c7bec2cfba6a3caf6c8757ea
- [ ] Перенести Телескопическую дубинку https://github.com/AdventureTimeSS14/space_station_ADT/pull/25 @Schrodinger71 

## Вырезание
- [x] Вырезать секреты корвакса https://github.com/AdventureTimeSS14/space_station_ADT/pull/6
- [x] https://github.com/AdventureTimeSS14/space_station_ADT/pull/23
- [ ] Заменить текстуры унатхов на визденовские
- [ ] Удалить текстуры одежды для унатхов

## Гит
- [ ] Поменять шаблоны задач
- [ ] Добавить плашки статуса для задач (lables)
- [x] Убить @themanyfaceddemon 
- [x] https://github.com/AdventureTimeSS14/space_station_ADT/pull/4
- [x] Доделать адекватно ченджлог
- [x] https://github.com/AdventureTimeSS14/space_station_ADT/pull/5
- [x] #44

## Расы
- [ ] #45
- [ ] #46
- [ ] #47
- [ ] Драски [Первый](https://github.com/xtray85/space_station/pull/152) [Второй](https://github.com/xtray85/space_station/pull/155) @nixsilvam404 https://github.com/AdventureTimeSS14/space_station_ADT/pull/28
- [ ] #48
- [ ] #49
- [ ] #50
- [ ] #51
- [ ] #52
- [ ] Тоже самое с Нианами

## Должности станции
- [ ] #55
- [ ] Перенести Патологиста(Мед) @Darki255  https://github.com/AdventureTimeSS14/space_station_ADT/pull/30
- [ ] #56
- [ ] #57
- [ ] #58
- [ ] Перенести Реворк Бригмеда https://github.com/xtray85/space_station/pull/740
- [ ] Перенести ОСЩ https://github.com/xtray85/space_station/pull/705
- [ ] Перенести Следователя СБ @Schrodinger71 https://github.com/AdventureTimeSS14/space_station_ADT/pull/25
- [ ] #59
- [ ] #60
- [ ] #61

## Механики, особое
~~- [ ] Перенести панель эмоций~~
- [ ] Перенести Болезни(Требуют тщательных тестов, оставить на последок) [ветка Модерна](https://github.com/modern-nm/space_station/tree/disease) 
~~- [ ] Перенос Мехов из секретки~~
- [ ] #65
- [ ] #66
- [ ] #67
- [ ] #68
- [ ] #69
- [ ] Перенести близорукость https://github.com/xtray85/space_station/pull/773

## Мапы
- [ ] #71
- [ ] #72
- [ ] #73
- [ ] Учитывать набор целей для каждой мапы как тут https://github.com/space-syndicate/space-station-14/pull/2338

## Админское
- [x] Adminwho не доступно смертным https://github.com/AdventureTimeSS14/space_station_ADT/pull/34 @Schrodinger71 
- [x] В админчате префиксы званий https://github.com/AdventureTimeSS14/space_station_ADT/pull/32 @Schrodinger71 
- [x] В ф1 префиксы званий админов https://github.com/AdventureTimeSS14/space_station_ADT/pull/31 @Schrodinger71 
- [ ] Требует тщательных тестов, пометка новичков https://github.com/xtray85/space_station/pull/743

## Трусы
- [ ] #76
- [ ] #8
- [ ]

**Comment by themanyfaceddemon** [comment]
kill @themanyfaceddemon is done

**Comment by FaDeOkno** [comment]
Панель эмоций переносить не надо, надо лишь допилить официальную чтоб там не стакались и не накладывались друг на друга кнопки

**Comment by Schrodinger71** [comment]
Угум, ты правь если что

**Comment by nixsilvam404** [comment]
пу пу, беру Драска пока

**Comment by Schrodinger71** [comment]
Займусь переносом Следователя СБ

**Comment by Darki255** [comment]
беру ADTPathologist

**Comment by Ratyyy** [comment]
занимаю спрайты

**Comment by AnderFan** [comment]
Гемофилию перенесу что-ли...

**Comment by Ratyyy** [comment]
начинаю перенос фелинидов

**Comment by AnderFan** [comment]
Беру Ниан
