### ISSUE TITLE
Необходимо переделать нижнее бельё, оно через жопу сделано. (UI слотов под нижнюю одежду вынесены в сторону)

### ISSUE THREAD

**Issue by Schrodinger71** [AdventureTimeSS14/space_station_ADT#8]
![image](https://github.com/AdventureTimeSS14/space_station_ADT/assets/132720404/1c280461-e232-490e-bc42-4ac62bde8655)

**Comment by themanyfaceddemon** [comment]
Это не только проблема. Проблема ещё с их флагами слотов да и сделано через говно

**Comment by FaDeOkno** [comment]
Берусь за перенос
