### ISSUE TITLE
Сабельные ножны ЦентКом(529 PR)

### ISSUE THREAD

**Issue by Schrodinger71** [AdventureTimeSS14/space_station_ADT#94]
Перенос https://github.com/AdventureTimeSS14/space_station/pull/529

Conflicts:
Resources/Locale/ru-RU/ADT/Clothing/Belt/belt.ftl
Resources/Prototypes/ADT/Entities/Clothing/Belt/belts.yml

**Comment by Bolper** [comment]
https://github.com/AdventureTimeSS14/space_station_ADT/pull/214
