### ISSUE TITLE
ERT роль Майор РХБЗЗ (728 PR)

### ISSUE THREAD

**Issue by Schrodinger71** [AdventureTimeSS14/space_station_ADT#98]
Перенос https://github.com/AdventureTimeSS14/space_station/pull/728

Conflicts:
Resources/Locale/ru-RU/ADT/ghost/roles/ghost-role.ftl
Resources/Prototypes/ADT/Entities/Mobs/player/humanoid.yml

**Comment by Schrodinger71** [comment]
@RipZoro1 Поставил дедлайн до 12.08.24 (включительно)

**Comment by Darki255** [comment]
> [@RipZoro1](https://github.com/RipZoro1) Поставил дедлайн до 12.08.24 (включительно)

Аннулировано

**Comment by Darki255** [comment]
будем отдуваться за зоро
